# Generated by Django 5.2.13 on 2026-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='avaliable_balance_in_paise',
            field=models.IntegerField(default=0),
        ),
    ]
