# Generated by Django 5.2.13 on 2026-04-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0003_merchant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='bank_account_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
